#ifndef CELLULO_LOCALIZATION_GLOBAL_H
#define CELLULO_LOCALIZATION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CELLULO_LOCALIZATION_LIBRARY)
#  define CELLULO_LOCALIZATIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CELLULO_LOCALIZATIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CELLULO_LOCALIZATION_GLOBAL_H
